sudo: required

dist: xenial

language: java

script:
  - ./crossbuild.sh clean install

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - curl -s -o ~/bin/install-jdk.sh "https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh"
  - chmod +x ~/bin/install-jdk.sh
  - ~/bin/install-jdk.sh --target "/home/travis/openjdk17" --workspace "/home/travis/.cache/install-jdk" --feature "17" --license "GPL" --cacerts
  - cp .travis-toolchains.xml ~/.m2/toolchains.xml